/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pas;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author Fine-Tune
 */
public class frm_adminhome extends javax.swing.JFrame {
//    generalclass ob=new generalclass();

    /**
     * Creates new form frm_adminhome
     */
    String unam="";
    public frm_adminhome(String val) {
        initComponents();
        unam=val;
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblview = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnviewuser = new javax.swing.JButton();
        btnappli = new javax.swing.JButton();
        btnmail = new javax.swing.JButton();
        btnsettings = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnstatus = new javax.swing.JButton();
        lblvi = new javax.swing.JLabel();
        lblapp = new javax.swing.JLabel();
        lblmail = new javax.swing.JLabel();
        lblset = new javax.swing.JLabel();
        lblsta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblview.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setText("WELCOME TO ADMIN........");

        btnviewuser.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnviewuser.setText("VIEW USERS");
        btnviewuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewuserActionPerformed(evt);
            }
        });

        btnappli.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnappli.setText("APPLICATIONS");
        btnappli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnappliActionPerformed(evt);
            }
        });

        btnmail.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnmail.setText("MAILS");
        btnmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmailActionPerformed(evt);
            }
        });

        btnsettings.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnsettings.setText("SETTINGS");
        btnsettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsettingsActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jButton5.setText("EXIT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnstatus.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnstatus.setText("STATUS");
        btnstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstatusActionPerformed(evt);
            }
        });

        lblvi.setText("VIEW USERS");
        lblvi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblviMouseClicked(evt);
            }
        });

        lblapp.setText("APPLICATIONS");

        lblmail.setText("MAILS");

        lblset.setText("SETTINGS");

        lblsta.setText("STATUS");

        javax.swing.GroupLayout lblviewLayout = new javax.swing.GroupLayout(lblview);
        lblview.setLayout(lblviewLayout);
        lblviewLayout.setHorizontalGroup(
            lblviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblviewLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblviewLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(lblviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnappli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnviewuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnstatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addGroup(lblviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblvi)
                    .addComponent(lblset)
                    .addComponent(lblmail)
                    .addComponent(lblapp)
                    .addComponent(lblsta))
                .addGap(236, 236, 236))
        );
        lblviewLayout.setVerticalGroup(
            lblviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblviewLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(lblviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(109, 109, 109)
                .addGroup(lblviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnviewuser)
                    .addComponent(lblvi))
                .addGap(34, 34, 34)
                .addGroup(lblviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblviewLayout.createSequentialGroup()
                        .addComponent(btnappli)
                        .addGap(30, 30, 30)
                        .addComponent(btnmail)
                        .addGap(32, 32, 32)
                        .addComponent(btnsettings)
                        .addGap(33, 33, 33)
                        .addComponent(btnstatus))
                    .addGroup(lblviewLayout.createSequentialGroup()
                        .addComponent(lblapp)
                        .addGap(27, 27, 27)
                        .addComponent(lblmail)
                        .addGap(34, 34, 34)
                        .addComponent(lblset)
                        .addGap(35, 35, 35)
                        .addComponent(lblsta)))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnappliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnappliActionPerformed
        // TODO add your handling code here:
        frm_viewapplication vi=new frm_viewapplication();
        vi.show();
        this.hide();
    }//GEN-LAST:event_btnappliActionPerformed

    private void btnsettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsettingsActionPerformed
        // TODO add your handling code here:
        frm_adminsettings as=new frm_adminsettings(unam);
        as.show();
        this.hide();
    }//GEN-LAST:event_btnsettingsActionPerformed

    private void btnviewuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewuserActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnviewuserActionPerformed

    private void btnmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmailActionPerformed
        // TODO add your handling code here:
        frm_mail m=new frm_mail(unam);
        m.show();
        this.hide();
    }//GEN-LAST:event_btnmailActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        frm_login oo=new frm_login();
        oo.show();
       this.hide();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstatusActionPerformed
        // TODO add your handling code here:
        frm_viewstatus vi=new frm_viewstatus();
        vi.show();
        this.hide();
    }//GEN-LAST:event_btnstatusActionPerformed

    private void lblviMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblviMouseClicked
        // TODO add your handling code here:
        frm_viewuserdetail v=new frm_viewuserdetail();
        v.show();
        this.hide();
    }//GEN-LAST:event_lblviMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_adminhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_adminhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_adminhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_adminhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_adminhome("").setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnappli;
    private javax.swing.JButton btnmail;
    private javax.swing.JButton btnsettings;
    private javax.swing.JButton btnstatus;
    private javax.swing.JButton btnviewuser;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblapp;
    private javax.swing.JLabel lblmail;
    private javax.swing.JLabel lblset;
    private javax.swing.JLabel lblsta;
    private javax.swing.JLabel lblvi;
    private javax.swing.JPanel lblview;
    // End of variables declaration//GEN-END:variables
}
