/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pas;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Fine-Tune
 */
public class frm_usersettings extends javax.swing.JFrame {
    generalclass ob=new generalclass();

    /**
     * Creates new form frm_usersettings
     */
    String user="";
    String pass="";
    public frm_usersettings(String val) {
        initComponents();
        user=val;
         Connection con=null;
       
        try
        {
          con=ob.getconnect();
          
          Statement st=con.createStatement();
          ResultSet rs=st.executeQuery("select pwd from user_table where login_id='"+user+"'");
          while(rs.next())
          {
              pass=rs.getString("pwd");
          }
        }
        catch(Exception ex)
        {
           System.out.print(ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblnew = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblold = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblcpwd = new javax.swing.JLabel();
        pfold = new javax.swing.JPasswordField();
        pfnew = new javax.swing.JPasswordField();
        pfcpwd = new javax.swing.JPasswordField();
        btnchange = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblnew.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("CHANGE PASSWORD......");

        lblold.setText("Old password");

        jLabel3.setText("New password");

        lblcpwd.setText("Confirm password");

        btnchange.setText("Change");
        btnchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchangeActionPerformed(evt);
            }
        });

        btnexit.setText("EXIT");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lblnewLayout = new javax.swing.GroupLayout(lblnew);
        lblnew.setLayout(lblnewLayout);
        lblnewLayout.setHorizontalGroup(
            lblnewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblnewLayout.createSequentialGroup()
                .addGroup(lblnewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblnewLayout.createSequentialGroup()
                        .addGroup(lblnewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lblnewLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(lblnewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblcpwd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblold, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(98, 98, 98)
                                .addGroup(lblnewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pfold, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                    .addComponent(pfnew)
                                    .addComponent(pfcpwd)))
                            .addGroup(lblnewLayout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(btnchange))
                            .addGroup(lblnewLayout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jLabel1)))
                        .addGap(0, 64, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblnewLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnexit)))
                .addContainerGap())
        );
        lblnewLayout.setVerticalGroup(
            lblnewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblnewLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(btnexit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addGroup(lblnewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblold)
                    .addComponent(pfold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(lblnewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pfnew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(lblnewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcpwd)
                    .addComponent(pfcpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnchange)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblnew, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblnew, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchangeActionPerformed
        // TODO add your handling code here:
         Connection con=null;
        String pass=pfold.getText();
        if(pass.equals(pass))
        {
            if(pfnew.getText().equals(pfcpwd.getText()))
            {
        try
        {
           con=ob.getconnect();
            Statement st=con.createStatement();
            st.executeUpdate("update user_table set pwd='"+pfcpwd.getText()+"',cpwd='"+pfcpwd.getText()+"' where login_id='"+user+"'");
            JOptionPane.showMessageDialog(this, "successfully changed...");
        }
        catch(Exception ex)
        {
           System.out.print(ex.toString());
        }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Password Mismatch....");
            }
        }
        else
        {
             JOptionPane.showMessageDialog(this, "Old Password Mismatch....");
        }
    }//GEN-LAST:event_btnchangeActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        frm_userhome uh=new frm_userhome(user);
        uh.show();
        this.hide();
    }//GEN-LAST:event_btnexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_usersettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_usersettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_usersettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_usersettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_usersettings("").setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchange;
    private javax.swing.JButton btnexit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblcpwd;
    private javax.swing.JPanel lblnew;
    private javax.swing.JLabel lblold;
    private javax.swing.JPasswordField pfcpwd;
    private javax.swing.JPasswordField pfnew;
    private javax.swing.JPasswordField pfold;
    // End of variables declaration//GEN-END:variables
}
