/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pas;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Fine-Tune
 */
public class frm_viewuserdetail extends javax.swing.JFrame {
    generalclass ob=new generalclass();

    /**
     * Creates new form frm_viewuserdetail
     */
    public frm_viewuserdetail() {
        initComponents();
        this.applicants();
    }
    public void applicants()
    {
        try
        {
            Connection con=ob.getconnect();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select name from user_table where status='NA'");
            while(rs.next())
            {
                cmbview.addItem(rs.getString("name"));
            }
        }
        catch(Exception ex)
        {
            System.out.print(ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbview = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        lbln = new javax.swing.JLabel();
        lblg = new javax.swing.JLabel();
        lbld = new javax.swing.JLabel();
        lblad = new javax.swing.JLabel();
        lblunam = new javax.swing.JLabel();
        lblcont = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lblgen = new javax.swing.JLabel();
        lbldob = new javax.swing.JLabel();
        lbladd = new javax.swing.JLabel();
        lbluname = new javax.swing.JLabel();
        lblcontact = new javax.swing.JLabel();
        btnapprove = new javax.swing.JButton();
        btnreject = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("user details");

        jLabel2.setText("view users");

        cmbview.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Select-" }));
        cmbview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbviewActionPerformed(evt);
            }
        });

        jLabel3.setText("USER DETAILS");

        lbln.setText("Name");

        lblg.setText("Gender");

        lbld.setText("DOB");

        lblad.setText("Address");

        lblunam.setText("Username");

        lblcont.setText("Contact");

        btnapprove.setText("Approve");
        btnapprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnapproveActionPerformed(evt);
            }
        });

        btnreject.setText("Reject");
        btnreject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrejectActionPerformed(evt);
            }
        });

        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(btnapprove)
                        .addGap(50, 50, 50)
                        .addComponent(btnreject))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(132, 132, 132)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbview, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                                .addComponent(btnback))))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel3))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbln)
                            .addComponent(lblg)
                            .addComponent(lbld)
                            .addComponent(lblad)
                            .addComponent(lblunam)
                            .addComponent(lblcont))
                        .addGap(104, 104, 104)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblcontact)
                            .addComponent(lbluname)
                            .addComponent(lbladd)
                            .addComponent(lbldob)
                            .addComponent(lblgen, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(89, 89, 89))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnback))
                .addGap(50, 50, 50)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addGap(20, 20, 20)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbln)
                    .addComponent(lblname))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblg)
                    .addComponent(lblgen))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbld)
                    .addComponent(lbldob))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblad)
                    .addComponent(lbladd))
                .addGap(73, 73, 73)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblunam)
                    .addComponent(lbluname))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcont)
                    .addComponent(lblcontact))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnapprove)
                    .addComponent(btnreject))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbviewActionPerformed
        // TODO add your handling code here:
        try
        {
        Connection con=ob.getconnect();
        String nam=cmbview.getSelectedItem().toString();
        Statement st=con.createStatement();
        ResultSet rs=st.executeQuery("select * from user_table where name='"+nam+"'");
        while(rs.next())
        {
            lblname.setText(rs.getString("name"));
            lblgen.setText(rs.getString("gender"));
            lbldob.setText(rs.getString("dob"));
            lbladd.setText(rs.getString("address"));
            lbluname.setText(rs.getString("login_id"));
            lblcontact.setText(rs.getString("contact"));
            
        }
        }
        catch(Exception ex)
        {
            
        }
    }//GEN-LAST:event_cmbviewActionPerformed

    private void btnapproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnapproveActionPerformed
        // TODO add your handling code here:
        try
        {
           Connection con=ob.getconnect();
           String nam=cmbview.getSelectedItem().toString();
           Statement st=con.createStatement();
           
           st.executeUpdate("update user_table set status='A' where name='"+nam+"'");
           
           JOptionPane.showMessageDialog(this ,"Approved...");
           this.hide();
           frm_viewuserdetail vi=new frm_viewuserdetail();
           vi.show();
//           cmbview.setSelectedIndex(0);
           
        }
        catch(Exception ex)
        {
            
        }
    }//GEN-LAST:event_btnapproveActionPerformed

    private void btnrejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrejectActionPerformed
        // TODO add your handling code here:
        try
        {
            Connection con=ob.getconnect();
             String nam=cmbview.getSelectedItem().toString();
             Statement st=con.createStatement();
           String unam=""; 
        ResultSet rs=st.executeQuery("select login_id from user_table where name='"+nam+"'");
        while(rs.next())
        {
            unam=rs.getString("login_id");
        }
             st.executeUpdate("update user_table set status='R' where name='"+nam+"'");
//             st.executeUpdate("delete from login_table where username='"+unam+"'");
             JOptionPane.showMessageDialog(this,"Rejected!!!");
              this.hide();
           frm_viewuserdetail vi=new frm_viewuserdetail();
           vi.show();
        }
        catch(Exception ex)
        {
            
        }
    }//GEN-LAST:event_btnrejectActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
            frm_adminhome ad=new frm_adminhome("");
            ad.show();     
            this.hide();
            // TODO add your handling code here:
    }//GEN-LAST:event_btnbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_viewuserdetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_viewuserdetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_viewuserdetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_viewuserdetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_viewuserdetail().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnapprove;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnreject;
    private javax.swing.JComboBox cmbview;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblad;
    private javax.swing.JLabel lbladd;
    private javax.swing.JLabel lblcont;
    private javax.swing.JLabel lblcontact;
    private javax.swing.JLabel lbld;
    private javax.swing.JLabel lbldob;
    private javax.swing.JLabel lblg;
    private javax.swing.JLabel lblgen;
    private javax.swing.JLabel lbln;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblunam;
    private javax.swing.JLabel lbluname;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
