/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pas;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Fine-Tune
 */
public class frm_mail extends javax.swing.JFrame {

    /**
     * Creates new form frm_mail
     */
    generalclass ob=new generalclass();
    String unam="";
    int role=0;
    int value;
    public frm_mail(String val) {
        initComponents();
        unam=val;
        this.inbox();
        this.outbox();
        this.drafts();
        if(unam.equals("adm999"))
        {
            role=1;
        }
        
    }
    
public void inbox()
{
    Connection con=null;
    DefaultTableModel dc;
    dc=(DefaultTableModel)tbinbox.getModel();
    dc.setRowCount(0);
    dc.setColumnCount(0);
    dc.addColumn("Message ID");
    dc.addColumn("sender");
    dc.addColumn("subject");
    dc.addColumn("Message");
    dc.addColumn("Date");
    try
    {
    con=ob.getconnect();
    Statement st=con.createStatement();
    ResultSet rs=st.executeQuery("select * from message_table where receiver='"+unam+"' and status='sent'");
    while(rs.next())
    {
        String id=rs.getString("ID");
        String sen=rs.getString("sender");
        String sub=rs.getString("subject");
        String message=rs.getString("message");
        String date=rs.getString("date");
        Object[] so={id,sen,sub,message,date};
        dc.addRow(so);
    }
    }
    catch(Exception ex)
    {
        System.out.print(ex.toString());
    }
}
public void outbox()
{
    Connection con=null;
    DefaultTableModel dc;
    dc=(DefaultTableModel)tboutbox.getModel();
    dc.setRowCount(0);
    dc.setColumnCount(0);
    dc.addColumn("Message ID");
    dc.addColumn("Receiver");
    dc.addColumn("Message");
    dc.addColumn("Date");
    
    try
    {
    con=ob.getconnect();
    Statement st=con.createStatement();
    ResultSet rs=st.executeQuery("select * from message_table where sender='"+unam+"' and status='sent'");
    while(rs.next())
    {
        String id=rs.getString("ID");
        String rec=rs.getString("receiver");
        String message=rs.getString("message");
        String date=rs.getString("date");
        Object[] so={id,rec,message,date};
        dc.addRow(so);
    }
    }
    catch(Exception ex)
    {
        System.out.print(ex.toString());
    }
}
public void drafts()
{
    Connection con=null;
    DefaultTableModel dc;
    dc=(DefaultTableModel)tbdraft.getModel();
    dc.setRowCount(0);
    dc.setColumnCount(0);
    dc.addColumn("Message ID");
    dc.addColumn("To");
    dc.addColumn("Message");
    dc.addColumn("Date");
    try
    {
    con=ob.getconnect();
    Statement st=con.createStatement();
    ResultSet rs=st.executeQuery("select * from message_table where sender='"+unam+"' and status='saved'");
    while(rs.next())
    {
        String id=rs.getString("ID");
        String rec=rs.getString("receiver");
        String message=rs.getString("message");
        String date=rs.getString("date");
        Object[] so={id,rec,message,date};
        dc.addRow(so);
    }
    }
    catch(Exception ex)
    {
        System.out.print(ex.toString());
    }
}
public int attachfile()
{
    System.out.print(value);
    int flag=0;
    Connection con=null;
     byte[] fileBytes=null;
    try
    {
        con=ob.getconnect();
        Statement st=con.createStatement();
        ResultSet rs=st.executeQuery("select attach from message_table where ID='"+value+"'");
        while(rs.next())
        {
          fileBytes=rs.getBytes(1);
         
        }
        if(fileBytes!=null)
        {
            flag=1;
        }
    }
    catch(Exception ex)
    {
        System.out.print(ex.toString());
    }
    return flag;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        path = new javax.swing.JFileChooser();
        fileattach = new javax.swing.JFileChooser();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tboutbox = new javax.swing.JTable();
        btndown = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbdraft = new javax.swing.JTable();
        btnsen = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        btndnld = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnbrowse = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnsend = new javax.swing.JButton();
        txtto = new javax.swing.JTextField();
        txtsub = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtmessage = new javax.swing.JTextArea();
        txtattach = new javax.swing.JTextField();
        lblstatus = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbinbox = new javax.swing.JTable();
        txtsearch = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        btndwn = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/mail.jpg"))); // NOI18N
        jLabel6.setText("Mails");

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/send mail3.jpg"))); // NOI18N
        jLabel7.setText("Send Items");

        tboutbox.setBackground(new java.awt.Color(204, 204, 204));
        tboutbox.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message ID", "Receiver ", "Message", "Date"
            }
        ));
        tboutbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tboutboxMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tboutbox);

        btndown.setText("DOWNLOAD");
        btndown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btndown)
                .addGap(48, 48, 48))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btndown)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Outbox", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/draft.png"))); // NOI18N
        jLabel8.setText("Saved Messages");

        tbdraft.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message ID", "To", "Message", "Date"
            }
        ));
        tbdraft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdraftMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbdraft);

        btnsen.setText("SEND");
        btnsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsenActionPerformed(evt);
            }
        });

        btndel.setText("DELETE");

        btndnld.setText("DOWNLOAD");
        btndnld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndnldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(btnsen, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(116, 116, 116)
                            .addComponent(btndnld)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btndel))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndel)
                    .addComponent(btnsen)
                    .addComponent(btndnld))
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("Drafts", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/new mail3.png"))); // NOI18N
        jLabel1.setText("Create New Message");

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("To");

        jLabel3.setText("Subject");

        jLabel4.setText("Message");

        jLabel5.setText("Attach");

        btnbrowse.setText("Browse");
        btnbrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbrowseActionPerformed(evt);
            }
        });

        btnsave.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnsend.setBackground(new java.awt.Color(255, 255, 255));
        btnsend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/send_email.png"))); // NOI18N
        btnsend.setText("SEND");
        btnsend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsendActionPerformed(evt);
            }
        });

        txtto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttoActionPerformed(evt);
            }
        });

        txtsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubActionPerformed(evt);
            }
        });

        txtmessage.setColumns(20);
        txtmessage.setRows(5);
        jScrollPane1.setViewportView(txtmessage);

        txtattach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtattachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(lblstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addComponent(txtsub, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtattach)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                                    .addComponent(txtto, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnbrowse)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(130, 130, 130)
                                .addComponent(btnsend)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtsub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtattach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbrowse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsend, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Create", jPanel4);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/inbox.jpg"))); // NOI18N
        jLabel9.setText("Your Mails!");

        tbinbox.setBackground(new java.awt.Color(204, 204, 204));
        tbinbox.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Message ID", "Sender", "Subject", "Message", "Date"
            }
        ));
        tbinbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbinboxMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbinbox);
        tbinbox.getColumnModel().getColumn(1).setResizable(false);

        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });

        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        btndwn.setText("Download");
        btndwn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndwnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnsearch)))
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btndwn)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsearch))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btndwn)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inbox", jPanel1);

        btnback.setBackground(new java.awt.Color(255, 255, 255));
        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/back.jpg"))); // NOI18N
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnback)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnback)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        
        if(role==0)
        {
            frm_userhome us=new frm_userhome(unam);
            us.show();
        }
        else
        {
            frm_adminhome ad=new frm_adminhome("");
            ad.show();
        }
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnsendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsendActionPerformed
        // TODO add your handling code here:
        try
        {
//            string date=date
            File file=new File(path.getSelectedFile().toString());
            FileInputStream fi=new FileInputStream(file);
            int len=(int) file.length();
            Connection con=null;
            con=ob.getconnect();
            PreparedStatement ps;
            String query="insert into message_table(sender,receiver,status,subject,message,attach,date)values(?,?,?,?,?,?,getdate())";
            ps=con.prepareStatement(query);
            ps.setString(1,unam);
            ps.setString(2,txtto.getText());
            ps.setString(3,"sent");
            ps.setString(4, txtsub.getText());
            ps.setString(5,txtmessage.getText());
            ps.setBinaryStream(6,fi,len);
            ps.executeUpdate();
            lblstatus.setText("Your message has been send....");
        }
        catch(Exception ex)
        {
         System.out.print(ex.toString());
        }
    }//GEN-LAST:event_btnsendActionPerformed

    private void btnbrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbrowseActionPerformed
        // TODO add your handling code here:
        int rtvl=path.showOpenDialog(this);
        String pa=path.getSelectedFile().toString();
        txtattach.setText(pa);
    }//GEN-LAST:event_btnbrowseActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        try
        {
            File file=new File(path.getSelectedFile().toString());
            FileInputStream fi=new FileInputStream(file);
            int len=(int) file.length();
            Connection con=null;
            con=ob.getconnect();
            PreparedStatement ps;
            String query="insert into message_table(sender,receiver,status,subject,message,attach,date)values(?,?,?,?,?,?,getdate())";
            ps=con.prepareStatement(query);
            ps.setString(1,unam);
            ps.setString(2,txtto.getText());
            ps.setString(3,"saved");
            ps.setString(4, txtsub.getText());
            ps.setString(5,txtmessage.getText());
            ps.setBinaryStream(6,fi,len);
            ps.executeUpdate();
            lblstatus.setText("Your message has been saved....");
        }
        catch(Exception ex)
        {
         System.out.print(ex.toString());
        } 
    }//GEN-LAST:event_btnsaveActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void btnsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsenActionPerformed
        // TODO add your handling code here:
//        Connection con=null;
//    try
//    {
//    con=ob.getconnect();
//    Statement st=con.createStatement();
//    st.executeUpdate("update messege_table set status='sent' where sender='"+unam+"'");
//    }
//    catch(Exception ex)
//    {
//        System.out.print(ex.toString());
//    }
    }//GEN-LAST:event_btnsenActionPerformed

    private void btndwnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndwnActionPerformed
        // TODO add your handling code here:
        Connection con=null;
        int att=attachfile();
        if(att==0)
        {
            JOptionPane.showMessageDialog(this,"No attachment found!!");
        }
        else
        {
         String mypath="";
        int reval=fileattach.showSaveDialog(this);
        if(reval==javax.swing.JFileChooser.APPROVE_OPTION)
        {
            mypath=fileattach.getCurrentDirectory().toString();
            generalclass ob=new generalclass();
            byte[] fileBytes;
            String query;
            con=ob.getconnect();
            try
            {
               query="select attach from message_table where ID='"+value+"'";
                Statement st=con.createStatement();
                ResultSet rs=st.executeQuery(query);
                if(rs.next())
                {
                    fileBytes=rs.getBytes(1);
                    OutputStream targetfile=new FileOutputStream(mypath+"//"+"uuu");
                    targetfile.write(fileBytes);
                    targetfile.close();
                }
                JOptionPane.showMessageDialog(this,"saved");
            }
            catch(Exception ex)
            {
                
            }
        }
      
        }
    
    }//GEN-LAST:event_btndwnActionPerformed

    private void tbinboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbinboxMouseClicked
        // TODO add your handling code here:
        int row=tbinbox.getSelectedRow();
        value=Integer.parseInt(tbinbox.getModel().getValueAt(row, 0).toString());
        attachfile();
    }//GEN-LAST:event_tbinboxMouseClicked

    private void btndownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndownActionPerformed
        // TODO add your handling code here:
     Connection con=null;
        int att=attachfile();
        if(att==0)
        {
            JOptionPane.showMessageDialog(this,"No attachment found!!");
        }
        else
        {
         String mypath="";
        int reval=fileattach.showSaveDialog(this);
        if(reval==javax.swing.JFileChooser.APPROVE_OPTION)
        {
            mypath=fileattach.getCurrentDirectory().toString();
            generalclass ob=new generalclass();
            byte[] fileBytes;
            String query;
            con=ob.getconnect();
            try
            {
               query="select attach from message_table where ID='"+value+"'";
                Statement st=con.createStatement();
                ResultSet rs=st.executeQuery(query);
                if(rs.next())
                {
                    fileBytes=rs.getBytes(1);
                    OutputStream targetfile=new FileOutputStream(mypath+"//"+"uuu");
                    targetfile.write(fileBytes);
                    targetfile.close();
                }
                JOptionPane.showMessageDialog(this,"saved");
            }
            catch(Exception ex)
            {
                
            }
        }
      
        }
       
    }//GEN-LAST:event_btndownActionPerformed

    private void tboutboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tboutboxMouseClicked
        // TODO add your handling code here:
      int row=tboutbox.getSelectedRow();
        value=Integer.parseInt(tboutbox.getModel().getValueAt(row, 0).toString());
        attachfile();  
    }//GEN-LAST:event_tboutboxMouseClicked

    private void btndnldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndnldActionPerformed
        // TODO add your handling code here:
      Connection con=null;
        int att=attachfile();
        if(att==0)
        {
            JOptionPane.showMessageDialog(this,"No attachment found!!");
        }
        else
        {
         String mypath="";
        int reval=fileattach.showSaveDialog(this);
        if(reval==javax.swing.JFileChooser.APPROVE_OPTION)
        {
            mypath=fileattach.getCurrentDirectory().toString();
            generalclass ob=new generalclass();
            byte[] fileBytes;
            String query;
            con=ob.getconnect();
            try
            {
               query="select attach from message_table where ID='"+value+"'";
                Statement st=con.createStatement();
                ResultSet rs=st.executeQuery(query);
                if(rs.next())
                {
                    fileBytes=rs.getBytes(1);
                    OutputStream targetfile=new FileOutputStream(mypath+"//"+"uuu");
                    targetfile.write(fileBytes);
                    targetfile.close();
                }
                JOptionPane.showMessageDialog(this,"saved");
            }
            catch(Exception ex)
            {
                
            }
        }
      
        }
          
    }//GEN-LAST:event_btndnldActionPerformed

    private void tbdraftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdraftMouseClicked
        // TODO add your handling code here:
     int row=tbdraft.getSelectedRow();
        value=Integer.parseInt(tbdraft.getModel().getValueAt(row, 0).toString());
        attachfile();     
    }//GEN-LAST:event_tbdraftMouseClicked

    private void txtsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsubActionPerformed

    private void txtattachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtattachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtattachActionPerformed

    private void txttoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttoActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsearchActionPerformed

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_mail("").setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnbrowse;
    private javax.swing.JButton btndel;
    private javax.swing.JButton btndnld;
    private javax.swing.JButton btndown;
    private javax.swing.JButton btndwn;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnsen;
    private javax.swing.JButton btnsend;
    private javax.swing.JFileChooser fileattach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblstatus;
    private javax.swing.JFileChooser path;
    private javax.swing.JTable tbdraft;
    private javax.swing.JTable tbinbox;
    private javax.swing.JTable tboutbox;
    private javax.swing.JTextField txtattach;
    private javax.swing.JTextArea txtmessage;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField txtsub;
    private javax.swing.JTextField txtto;
    // End of variables declaration//GEN-END:variables
}
